// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHU8ynMFoqGh1vHhvR6R86_0gui2Wh1UY',
    appId: '1:489048714731:web:2e584cab278f2549117dae',
    messagingSenderId: '489048714731',
    projectId: 'merkapp-e9d7b',
    authDomain: 'merkapp-e9d7b.firebaseapp.com',
    storageBucket: 'merkapp-e9d7b.appspot.com',
    measurementId: 'G-LPNLW0DH2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYHt38LGIBeB4wCwOvr5cQNLdYtZxrL-E',
    appId: '1:489048714731:android:16613f79b5cbb206117dae',
    messagingSenderId: '489048714731',
    projectId: 'merkapp-e9d7b',
    storageBucket: 'merkapp-e9d7b.appspot.com',
  );
}
